name: Zip Files - create file for update.

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: create forder setup
        run: mkdir -p setup
      - name: Zip Files App desktop
        run: |
          cd AppDesktopLatestVersion
          zip -r ../setup/AppDesktopLatestVersion.zip . -x "*/logs/*"
        working-directory: ${{ github.workspace }}
      - name: Zip Files Service
        run: |
          cd ServiceLastestVersion
          zip -r ../setup/ServiceLastestVersion.zip . -x "*/logs/*"
        working-directory: ${{ github.workspace }}
      - name: Commit changes
        run: |
          git config --global user.email "tiephoang.dev@gmail.com"
          git config --global user.name "tiephoang.dev@gmail.com"
          git checkout main
          git add .
          git commit -m "Zip Files - create file for update."
          git push -u origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Send Telegram notification
        run: |
          curl -X POST \
            -H 'Content-Type: application/json' \
            -d '{
              "chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}",
              "text": "New version KSP3 updated. Please update to new version! - tiephoang.dev."
            }' \
            https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage
            
