name: Zip Files

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Zip Files
        run: |
          cd FileLatestVersion
          zip -r ../setup/setup.zip .
        working-directory: ${{ github.workspace }}
      - name: Commit changes
        run: |
          git config --global user.email "<your-email>"
          git config --global user.name "<your-username>"
          git checkout -b main
          git add .
          git commit -m "Commit message"
          git push -u origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
