name: Zip Files - create file for update.

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Zip Files
        run: |
          cd FileLatestVersion
          zip -r ../setup/setup.zip $(find . grep -v "./logs/*")
        working-directory: ${{ github.workspace }}
      - name: Commit changes
        run: |
          git config --global user.email "tiephoang.dev@gmail.com"
          git config --global user.name "tiephoang.dev@gmail.com"
          git checkout main
          git add .
          git commit -m "Zip Files - create file for update."
          git push -u origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: 'New version KSP3 updated. Please go to "Dev>Check for update" for update new version! - tiephoang.dev.'       