name: Notify Telegram on Issue Change
on:
  issues:
    types: [opened, edited, reopened, closed]
  issue_comment:
    types:
      - created
jobs:
  telegram-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification
        run: |
          curl -X POST \
          -H 'Content-Type: application/json' \
          -d '{
            "chat_id": "${{ secrets.TELEGRAM_CHAT_ID }}",
            "text": "Issue #${{ github.event.issue.number }} - ${{github.event.issue.title}} (${{github.event.issue.html_url}}) has been ${{ github.event.action }} by ${{github.event.issue.user.login}} (${{github.event.issue.user.html_url}})"
          }' \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage
          