name: Notify on issue change
on:
  issues:
    types: [opened, edited, reopened]

jobs:
  issue-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Notify on issue change
        uses: mshick/add-or-update-comment@v1
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            Issue #${{ github.event.issue.number }} has been updated.
            Title: ${{ github.event.issue.title }}
            Link: ${{ github.event.issue.html_url }}