name: Notify Telegram on Issue Change
on:
  issues:
    types: [opened, edited, reopened, closed]
  issue_comment:
    types:
      - created

jobs:
  telegram-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "TELEGRAM_CHAT_ID=${{ TELEGRAM_CHAT_ID }}"
          echo "TELEGRAM_BOT_TOKEN=${{ TELEGRAM_BOT_TOKEN }}"
          echo "secrets.TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}"
          echo "secrets.TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}"
          
